### ISSUE TITLE
Neckweld Broken

### ISSUE THREAD

**Issue by TitanXii** [client/2r2t#10] opened 2021-01-12 15:06 UTC
Neckweld is fucking broken and has been for the longest time

you can't text anything in roblox studio because its stuck on "Loading", "Loading Inventory", or "Loading HUD"

**Comment by client** [comment] 2021-01-12 15:09
This is a duplicate of https://github.com/client/2r2t/issues/2

**Closed as completed by client** 2021-01-12 15:09 UTC
Labels: duplicate
